version: '3.9'
services:
  db_postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_INT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - medicapp_network

  db_pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - medicapp_network

  medicapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db_postgres
    environment:
      CREDENTIALS_ADMIN_USERNAME: ${APP_ADMIN_USER}
      CREDENTIALS_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      CREDENTIALS_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      CLOUD_AWS_CREDENTIALS_ACCESS-KEY: ${AWS_ACCESS_KEY_ID}
      CLOUD_AWS_CREDENTIALS_SECRET-KEY: ${AWS_SECRET_ACCESS_KEY}
      CLOUD_AWS_REGION_STATIC: ${AWS_REGION}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:${POSTGRES_PORT_INT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_MAIL_HOST: ${MAIL_SMTP_HOST}
      SPRING_MAIL_PORT: ${MAIL_SMTP_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_SMTP_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_SMTP_PASSWORD}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
    networks:
      - medicapp_network

volumes:
  postgres-data:

networks:
    medicapp_network:
        driver: bridge