package com.medicapp.server.doctors.model;

public enum Specialty {

    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    HEMATOLOGY,
    INFECTIOUS_DISEASE,
    NEPHROLOGY,
    NEUROLOGY,
    OBSTETRICS_AND_GYNECOLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIOLOGY,
    RHEUMATOLOGY,
    UROLOGY
}
