name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: 724218931517.dkr.ecr.sa-east-1.amazonaws.com/murphy-registry
  ECR_REPOSITORY: murphy-registry
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
 

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push
