name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY_PSQL: ${{secrets.ECR_REPOSITORY_PSQL }}
  ECR_REPOSITORY_SPRING: ${{ secrets.ECR_REPOSITORY_SPRING }}
  IMAGE_TAG: latest
  AWS_REGION: ${{secrets.ECR_AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create .env File
        run: |
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_PORT_INT=${{ secrets.POSTGRES_PORT_INT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "PGADMIN_PORT=${{ secrets.PGADMIN_PORT }}" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=${{secrets.PGADMIN_DEFAULT_EMAIL}}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{secrets.PGADMIN_DEFAULT_PASSWORD}}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "APP_ADMIN_USER=${{ secrets.APP_ADMIN_USER }}" >> .env
          echo "APP_ADMIN_PASSWORD=${{ secrets.APP_ADMIN_PASSWORD }}" >> .env
          echo "APP_ADMIN_EMAIL=${{ secrets.APP_ADMIN_EMAIL }}" >> .env
          echo "MAIL_SMTP_HOST=${{ secrets.MAIL_SMTP_HOST }}" >> .env
          echo "MAIL_SMTP_PORT=${{ secrets.MAIL_SMTP_PORT }}" >> .env
          echo "MAIL_SMTP_USERNAME=${{ secrets.MAIL_SMTP_USERNAME }}" >> .env
          echo "MAIL_SMTP_PASSWORD=${{ secrets.MAIL_SMTP_PASSWORD }}" >> .env

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 54.233.195.2 >> ~/.ssh/known_hosts

      - name: Create directory
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.233.195.2 "mkdir -p ./murphy-server"

      - name: Copy .env file
        run: |
          scp -i ~/.ssh/id_rsa .env ec2-user@54.233.195.2:./murphy-server/

      - name: Pull from repository
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.233.195.2 "cd ./murphy-server && git pull origin main"

      - name: Start Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.233.195.2 "cd ./murphy-server && docker-compose up -d"
